### ISSUE TITLE
when view a user and clicking on add as friend button (when not logged in) the message says Array instead of Please login to add as Friend"

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#138]
when view a user and clicking on add as friend button (when not logged in) the message says Array instead of Please login to add as Friend"

- ![Capture1](https://user-images.githubusercontent.com/17736688/84000903-34a2e500-a92b-11ea-8eba-3d9f9d80f2d2.PNG)

- ![Capture](https://user-images.githubusercontent.com/17736688/84000901-34a2e500-a92b-11ea-84ed-7e4eda77d251.PNG)

**Comment by MacWarrior** [comment]
Hi, 

Thanks for report !
Fixing this asap !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi,

From my side, I had a SQL error (fixed in last commit), but message show correctly
Can you check with last revision ?

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
Not working for me If I did everything correctly it still shows **Array**

**Comment by spirogg** [comment]
@MacWarrior PS I sent you a little something - Enough to buy you a little lunch. just trying to say thanks and to let you know I appreciate your work :) 
thanks again for fixing things.

**Comment by MacWarrior** [comment]
Hi,

I feel very sorry... I didn't read the title correctly 🤦
Last update should (really) fix this issue ! 😉

Thanks again !

Best regards,
MacWarrior.
