### ISSUE TITLE
Can't upload video

### ISSUE THREAD

**Issue by BanuBurkhairi** [MacWarrior/clipbucket-v5#221]
Can't upload video with .MP4, .MPEG. 

Just .mp4 can be uploade

**Comment by joo4mart** [comment]
You could rename the suffix from uppercase to lowercase ...

**Comment by MacWarrior** [comment]
Hello @BanuBurkhairi, 

Issue has been fixed on last commit

Best regards,
MacWarrior.

**Comment by BanuBurkhairi** [comment]
thanks for fixing this problem. Now, .mp4 , .webm and .mkv can be uploaded

but I still can't upload videos with .MP4 , .mpeg , .mpg,  extensions (FYI, the .MP4 format is a pure extension from my camera when recording)

**Comment by MacWarrior** [comment]
😮

I'll check this... !

**Comment by MacWarrior** [comment]
Can you confirme these extensions are allowed in video extensions ?

Like this : 
![image](https://user-images.githubusercontent.com/200590/156745639-8b6066ec-5bc8-48a5-9081-32e65a912239.png)

Extensions should not be case sensitive.

Also, are you uploading files from front office or from mass upload (back office) ?

Best regards,
MacWarrior.

**Comment by BanuBurkhairi** [comment]
![image](https://user-images.githubusercontent.com/78917748/156747951-fd854c7e-ec70-41ad-8236-478b0b4a8359.png)
this is when I upload one of the videos with the extension .MP4

![image](https://user-images.githubusercontent.com/78917748/156748280-c234755e-4b04-498a-8aa0-eef74fcbd7b4.png)
this is when the previous video I changed the extension to .mp4 and still can't upload it

![image](https://user-images.githubusercontent.com/78917748/156748772-b17a7ab3-edee-42d4-996f-28403f39925b.png)
this is the attachment when i upload it with normal .mp4 extension

My "allowed video extensions" is same with you. 

Sorry, I don't understand what you mean by front office or back office. and sorry for my bad english too

**Comment by spirogg** [comment]
@BanuBurkhairi front office he means front end. Going to your website and click upload video 

Back office he means backend 
He means mass upload videos to folder and in admin area you can mass upload those videos. 

Hope this helps understand :)

**Comment by MacWarrior** [comment]
Thanks @spirogg ; I really thought it was english terms.... I had to read your last comment to realize those are english words used by french people as french words... 😅


@BanuBurkhairi Can you retry with last commit ?
I uploaded a .MP4 file without any specific issue

Best regards,
MacWarrior.

**Comment by BanuBurkhairi** [comment]
@MacWarrior I still can't upload the .MP4
![gambar](https://user-images.githubusercontent.com/78917748/156971199-1187889d-efc5-4866-96d9-940bdf3a3d70.png)

You can use the video in the following link to be used as a reference for uploading. Because I still fail
https://drive.google.com/drive/folders/1dA1Em-D2ioEJU5jInk_JT_EsQGVIprCZ

**Comment by MacWarrior** [comment]
Hello @BanuBurkhairi,

I have issues with your files (at least the one I downloaded) too ; but not related with extension check
It looks some strange behaviors with large files... investigating...

That's even more strange because I work daily with 4-20Go files without this kind of issues, but on my prod env and not dev ....

Best regards,
MacWarrior.

**Comment by BanuBurkhairi** [comment]
I have done as you said before. And I still can't upload.
If there is a problem with large files. I can upload videos with a size of 600mb with the extension .webm

Is this really not fixable or is there a problem with ffmpeg?

**Comment by MacWarrior** [comment]
Hello @BanuBurkhairi, 

If video isn't created on admin area (even with failed status), then you have PHP/SQL errors, and I need them to understand what's happening on your configuration

If video is created on admin area, then I need your conversion log file

Please also confirm you're up-to-date with version 5.5.0, revision 61 (Admin area > Dashboard > Update status)

Best regards,
MacWarrior.

**Comment by BanuBurkhairi** [comment]
Yes i am up-to-date with version 5.5.0, revision 61

Sorry for my programming skills which are still beginners. Where can I see the configuration of the PHP/SQL errors and conversion log files?

**Comment by MacWarrior** [comment]
Hello @BanuBurkhairi, 

PHP logs file depends of your system configuration
By default on debian/ubuntu, you can check in /var/log/

Best regards,
MacWarrior.

**Comment by joo4mart** [comment]
First, I have converted one of these video files to make it smaller, again as x265 (hevc):

> Duration: 00:00:20.65, start: 0.000000, bitrate: 122903 kb/s
> Stream #0:0(eng): Video: hevc (Rext) (hev1 / 0x31766568), yuv422p10le(pc, bt709/bt709/unknown, progressive), 
>      4096x2160, 122898 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)

Second, I uploaded this file into clipbucketv5. But when I try to watch the video, unfortunately a browser error message comes up (firefox, the same as vivaldi): 

> The video could not be loaded because either a server or network error occurred or the format is not supported.

**Comment by joo4mart** [comment]
After some more tests I was finally able to import the original test video. It was exactly one value that needs to be set in the admin frontend: Website Configurations -> Conversion:
> "Max upload file size" to a higher value, e.g. 1600 (MiB). 

In other cases, the duration would have to be changed: Website Configurations -> Upload:
> "Max video duration" to a higher value, e.g. 400 [minutes].

And the php configuration must be set to higher values:
> post_max_size = 800M
> upload_max_filesize = 1600M

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Looks like some custom errors need to be implemented to alert users if file is too big
I'll check what I can do about it 😉 

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Upload forms has been updates on last commit to make them respect configured sizes limitations

Best regards,
MacWarrior.

**Comment by orlovskyjavaprofi** [comment]
Something wrong with upload form , smaller videos get trough but bigger dont, i done same php.ini setup and i dont understand whats going on i use latest dev version of clipbucket.
